### ISSUE TITLE
signed package are not reconized

### ISSUE THREAD

**Issue by mbonani** [aseba-community/aseba-osx#2]
People still have warning that packet are not correctly signed, specially in OSX11

**Comment by stephanemagnenat** [comment]
Since commit 8a36ca1de8790510a4a13578f3a3a934a6a10115 this problem should be corrected, please test and close.

**Comment by mbonani** [comment]
works on 10.11.4 El capitan. I will try to test on all version I have arround. 
If you have a version is still not test thanks to add  a comment here

**Comment by mbonani** [comment]
works on
10.6.8
10.8.4
10.10.2
10.12.1 Sierra Yes!

**Comment by stephanemagnenat** [comment]
Fixed.
